;;; test_xfer.el --- test xfer utilities
;; Copyright (C) 2018, 2020  Dan Harms (dharms)
;; Author: Dan Harms <enniomore@icloud.com>
;; Created: Tuesday, October 30, 2018
;; Version: 1.0
;; Modified Time-stamp: <2020-04-21 10:30:48 dharms>
;; Modified by: Dan Harms
;; Keywords: tools
;; URL: https://github.com/articuluxe/xfer.git
;; Package-Requires: ((emacs "25.1"))

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:
;; Test xfer file transfer utilities.
;;

;;; Code:
(load-file "test/xfer-test-common.el")
(require 'xfer)
(require 'xfer-util)

(ert-deftest xfer-test-same-hostname-p ()
  (should (xfer-util-same-hostname-p "mars" "mars"))
  (should (not (xfer-util-same-hostname-p "sweater" "cardigan")))
  (should (xfer-util-same-hostname-p "mars" "mars.company.local"))
  (should (xfer-util-same-hostname-p "MARS" "mars.company.local"))
  (should (not (xfer-util-same-hostname-p "sweater" "cardigan.comp.local")))
  )

(ert-deftest xfer-test-is-compressed-p ()
  (should (xfer-file-compressed-p "test.zip"))
  (should (xfer-file-compressed-p "test.gz"))
  (should (xfer-file-compressed-p "test.rar"))
  (should (not (xfer-file-compressed-p "test")))
  )

(ert-deftest xfer-test-compression ()
  (let* ((stage (concat base-test-dir "stage/"))
         (file "test_xfer.el")
         (src (concat base-test-dir file))
         result)
    (delete-directory stage t)
    (make-directory stage t)
    (copy-file src stage)
    (setq result
          (xfer-compress-file (concat stage file) nil 'zip))
    (should result)
    (should (file-exists-p result))
    (should (string= (file-name-extension result) "zip"))
    (should-error
     (xfer-compress-file result nil 'zip)
     :type 'user-error)
    (setq result (xfer-uncompress-file result))
    (should (file-exists-p result))
    (should (string= (file-name-nondirectory result)
                     file))
    (delete-directory stage t)
    )
  (let* ((stage (concat base-test-dir "stage/"))
         (file "test_xfer.el")
         (src (concat base-test-dir file))
         result)
    (delete-directory stage t)
    (make-directory stage t)
    (copy-file src stage)
    (setq result
          (xfer-compress-file (concat stage file) nil 'gzip))
    (should-error
     (xfer-compress-file result nil 'gzip)
     :type 'user-error)
    (should result)
    (should (file-exists-p result))
    (should (string= (file-name-extension result) "gz"))
    (setq result (xfer-uncompress-file result))
    (should (file-exists-p result))
    (should (string= (file-name-nondirectory result)
                     file))
    (delete-directory stage t)
    )
  (let* ((stage (concat base-test-dir "stage/"))
         (file "test_xfer.el")
         (src (concat base-test-dir file))
         result)
    (delete-directory stage t)
    (make-directory stage t)
    (copy-file src stage)
    (should-error
     (xfer-compress-file (concat stage file) nil 'missing)
     :type 'user-error)
    (delete-directory stage t)
    )
  (let* ((stage (concat base-test-dir "stage/"))
         (file "test_xfer.el")
         (src (concat base-test-dir file))
         result)
    (delete-directory stage t)
    (make-directory stage t)
    (copy-file src stage)
    (setq result
          (xfer-compress-file (concat stage file) nil '(missing t)))
    (should-error
     (xfer-compress-file result nil 'gzip)
     :type 'user-error)
    (should result)
    (should (file-exists-p result))
    (should (or (string= (file-name-extension result) "gz")
                (string= (file-name-extension result) "zip")))
    (setq result (xfer-uncompress-file result))
    (should (file-exists-p result))
    (should (string= (file-name-nondirectory result)
                     file))
    (delete-directory stage t)
    )
  )

(ert-deftest xfer-test-transfer-no-compression ()
  (let ()
    (cl-letf (((symbol-function 'xfer--should-compress)
               (lambda (_1 _2 _3 _4)
                 nil)))
      (let ((src (concat base-test-dir "test_xfer.el"))
            (dst (concat base-test-dir "stage/copy.el")))
        (delete-directory (concat base-test-dir "stage") t)
        (xfer-transfer-file src dst 'standard)
        (should (file-directory-p (concat base-test-dir "stage")))
        (should (file-exists-p dst)))
      (let ((src (concat base-test-dir "test_xfer.el"))
            (dst (concat base-test-dir "stage/copy.el")))
        (delete-directory (concat base-test-dir "stage") t)
        (xfer-transfer-file src dst '(standard))
        (should (file-directory-p (concat base-test-dir "stage")))
        (should (file-exists-p dst)))
      (let ((src (concat base-test-dir "test_xfer.el"))
            (dst (concat base-test-dir "stage/copy.el")))
        (delete-directory (concat base-test-dir "stage") t)
        (xfer-transfer-file src dst '(standard scp))
        (should (file-directory-p (concat base-test-dir "stage")))
        (should (file-exists-p dst)))
      (let ((src (concat base-test-dir "test_xfer.el"))
            (dst (concat base-test-dir "stage/copy.el")))
        (delete-directory (concat base-test-dir "stage") t)
        (xfer-transfer-file src dst 'scp)
        (should (file-directory-p (concat base-test-dir "stage")))
        (should (file-exists-p dst)))
      (let ((src (concat base-test-dir "test_xfer.el"))
            (dst (concat base-test-dir "stage/copy.el")))
        (delete-directory (concat base-test-dir "stage") t)
        (xfer-transfer-file src dst '(scp))
        (should (file-directory-p (concat base-test-dir "stage")))
        (should (file-exists-p dst)))
      (let ((src (concat base-test-dir "test_xfer.el"))
            (dst (concat base-test-dir "stage/copy.el")))
        (delete-directory (concat base-test-dir "stage") t)
        (xfer-transfer-file src dst '(scp standard))
        (should (file-directory-p (concat base-test-dir "stage")))
        (should (file-exists-p dst)))
      (let ((src (concat base-test-dir "test_xfer.el"))
            (dst (concat base-test-dir "stage/")))
        (delete-directory (concat base-test-dir "stage") t)
        (xfer-transfer-file src dst)
        (should (file-directory-p (concat base-test-dir "stage")))
        (should (file-exists-p dst))
        (should (file-regular-p (concat dst "test_xfer.el"))))
      ;nonexistent source
      (let ((src (concat base-test-dir "nonexistent"))
            (dst (concat base-test-dir "stage/")))
        (should-error
         (xfer-transfer-file src dst)
         :type 'user-error)))
    (delete-directory (concat base-test-dir "stage") t)))


(ert-deftest xfer-test-transfer-with-compression ()
  (let ()
    (cl-letf (((symbol-function 'xfer--should-compress)
               (lambda (_1 _2 _3 _4)
                 t)))
      (let ((src (concat base-test-dir "test_xfer.el"))
            (dst (concat base-test-dir "stage/copy.el")))
        (delete-directory (concat base-test-dir "stage") t)
        (xfer-transfer-file src dst 'standard)
        (should (file-directory-p (concat base-test-dir "stage")))
        (should (file-exists-p dst)))
      (let ((src (concat base-test-dir "test_xfer.el"))
            (dst (concat base-test-dir "stage/copy.el")))
        (delete-directory (concat base-test-dir "stage") t)
        (xfer-transfer-file src dst 'standard 'zip)
        (should (file-directory-p (concat base-test-dir "stage")))
        (should (file-exists-p dst)))
      (let ((src (concat base-test-dir "test_xfer.el"))
            (dst (concat base-test-dir "stage/copy.el")))
        (delete-directory (concat base-test-dir "stage") t)
        (xfer-transfer-file src dst 'standard 'gzip)
        (should (file-directory-p (concat base-test-dir "stage")))
        (should (file-exists-p dst)))
      (let ((src (concat base-test-dir "test_xfer.el"))
            (dst (concat base-test-dir "stage/copy.el")))
        (delete-directory (concat base-test-dir "stage") t)
        (xfer-transfer-file src dst 'scp 'zip)
        (should (file-directory-p (concat base-test-dir "stage")))
        (should (file-exists-p dst)))
      (let ((src (concat base-test-dir "test_xfer.el"))
            (dst (concat base-test-dir "stage/copy.el")))
        (delete-directory (concat base-test-dir "stage") t)
        (xfer-transfer-file src dst 'scp 'gzip)
        (should (file-directory-p (concat base-test-dir "stage")))
        (should (file-exists-p dst)))
      (let ((src (concat base-test-dir "test_xfer.el"))
            (dst (concat base-test-dir "stage/")))
        (delete-directory (concat base-test-dir "stage") t)
        (xfer-transfer-file src dst)
        (should (file-directory-p (concat base-test-dir "stage")))
        (should (file-exists-p dst))
        (should (file-regular-p (concat dst "test_xfer.el"))))
      (let ((src (concat base-test-dir "nonexistent"))
            (dst (concat base-test-dir "stage/")))
        (should-error
         (xfer-transfer-file src dst)
         :type 'user-error)))
    (delete-directory (concat base-test-dir "stage") t)))

;;; test_xfer.el ends here
